services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      retries: 5

  client-build:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run build"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./server/.env
    environment:
      DB_HOST: db
      NODE_ENV: production
      PORT: 5000
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    depends_on:
      db:
        condition: service_healthy
      client-build:
        condition: service_completed_successfully
    volumes:
      - ./client/dist:/app/client-dist:ro
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/usr/share/nginx/html:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - server

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  pgdata: